
  - name: Update apt package cache
    apt:
      update_cache: yes
      upgrade: yes

  - name: Install Apache
    apt:
      name: apache2
      state: present

  - name: Start Apache service
    service:
      name: apache2
      state: started